---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cheat_sheets":
    get:
      summary: list cheat_sheets
      responses:
        '200':
          description: successful
    post:
      summary: create cheat_sheet
      consumes:
      - application/json
      parameters:
      - in: body
        schema:
          type: object
          properties:
            key_stroke:
              type: string
            result:
              type: string
          required:
          - key_stroke
          - result
      responses:
        '200':
          description: successful
  "/random":
    get:
      summary: random cheat_sheet
      responses:
        '200':
          description: successful
