---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cheat_sheets":
    get:
      summary: return all or search for cheat_sheet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: object
          properties:
            search:
              type: string
      responses:
        '200':
          description: successful
    post:
      summary: create cheat_sheet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: data
        in: query
        schema:
          type: object
          properties:
            key_stroke:
              type: string
            result:
              type: string
      responses:
        '200':
          description: successful
  "/cheat_sheets/4":
    get:
      summary: show cheat_sheet
      responses:
        '200':
          description: successful
    patch:
      summary: update cheat_sheet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: data
        in: query
        schema:
          type: object
          properties:
            key_stroke:
              type: string
            result:
              type: string
      responses:
        '200':
          description: successful
    delete:
      summary: delete cheat_sheet
      responses:
        '200':
          description: successful
  "/random":
    get:
      summary: random cheat_sheet
      responses:
        '200':
          description: successful
